mails:
  from: contact@cerbereapp.com

plans:
  default: trial
  list:
    trial:
      max_employees: 3
      mail_notifications_enabled: false
      monthly_price: 0
    silver:
      max_employees: 100
      mail_notifications_enabled: false
      monthly_price: 99
    vip:
      max_employees: unlimited
      mail_notifications_enabled: true
      monthly_price: 149
