# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 2

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

# you can override concurrency based on environment
production:
  :concurrency: 2
staging:
  :concurrency: 2
